### PR TITLE
made plugin compatible with plugin Mantis Core Formatting

### PR DESCRIPTION
**Pull request by FSD-Christian-ADM**
removed some function calls for formatting so it is compatible with the Mantis Core Formatting Plugin

tested with MantisBT 2.21.0, BBCode+ 2.1.3, MantisBT-Formatting 2.21.0

no other functions seem to be lost

### CODE REVIEW

**Comment by bkraul** [comment]
Christian, thanks for the PR. However, I have some observations:

The plugin currently allows for use with or without Mantis Core Formatting plugin enabled. It adapts the actions according to whether the plugin is detected as enabled. This is by design. For example `string_strip_hrefs` is not part of MantisFormating plugin, but it is found on `core/string_api.php (568)`, which means it will work no matter what.

The reason I strip the hrefs is because I need them to be handled uniformly before I proceed to process the BBCode.

As such, unless this is currently causing a problem (I am aware and trying to find time to address related issue #62) , there is really no need for this PR.

**Comment by FSD-Christian-ADM** [comment]
We had the issue that links to other mantisbt installation became unclickable. they looked like `http://othermantis.test/#12345`
with my changes this seems to be fixed as well as keeping functionality of BBCode, mantis-internal links like #12345 or ~6789 and clickable url of any kind

**Comment by bkraul** [comment]
Christian, I will look at this more in detail. I see your point on your particular case. Also, as a reminder, please check out the [contributing guide](https://github.com/mantisbt-plugins/BBCodePlus/wiki/Contributing-to-BBCodePlus) (specifically the feature/dev branching model vs. PR from master to master).

**Comment by bkraul** [comment]
Closed in lieu of #66.

**Pull request closed without merging**
